site:
  title: Asset Administration Shell Documentation
  url: https://rwth-iat.github.io/aas-specs-antora
  start_page: index::index.adoc

content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: https://github.com/admin-shell-io/aas-specs
      branches: [IDTA-01001-3-0_antora_ref, IDTA-01001-3-1_working]
      start-paths: documentation/IDTA-01001
    - url: https://github.com/admin-shell-io/aas-specs-api
      branches: [IDTA-01002-3-0_antora_ref, IDTA-01002-3-1_preparation]
      start-paths: documentation/IDTA-01002-3
    - url: https://github.com/admin-shell-io/aas-specs-iec61360
      branches: [IDTA-01003-a-3-0_antora_ref, IDTA-01003-a-3-1_working]
      start-paths: documentation/IDTA-01003-a
    - url: https://github.com/admin-shell-io/aas-specs-aasx
      branches: [IDTA-01005-3-0_antora_ref, IDTA-01005-3-1_working]
      start-paths: documentation/IDTA-01005
    - url: https://github.com/rwth-iat/aas-specs-mock
      branches: [main]
      start-paths: 1/documentation/IDTA-02036
    - url: https://github.com/rwth-iat/aas-specs-mock
      branches: [main]
      start-paths: 2/documentation/IDTA-02036
      
ui:
  bundle:
    url: https://github.com/rwth-iat/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
    
runtime:
  fetch: true
  
antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/pdf-extension'

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
