site:
  title: Asset Administration Shell Documentation
  url: https://admin-shell-io.github.io/aas-specs-antora
  start_page: index::index.adoc

content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: /mnt/c/Users/igor/PycharmProjects/aas-specs
      branches:
        - IgGa/minorFixesTest
      start-paths: documentation/IDTA-01001
#    - url: /mnt/c/Users/igor/PycharmProjects/aas-specs-api
#      branches:
#        - IgGa/minorFixes
#      start-paths: documentation/IDTA-01002-3
#    - url: https://github.com/admin-shell-io/aas-specs-iec61360
#      branches:
#        - IDTA-01003-a-3-1_working
#      start-paths: documentation/IDTA-01003-a
#    - url: https://github.com/admin-shell-io/aas-specs-aasx
#      branches:
#        - IDTA-01005-3-1_working
#      start-paths: documentation/IDTA-01005

ui:
  bundle:
    url: https://github.com/admin-shell-io/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll

runtime:
  fetch: true

antora:
  extensions:
    - '@antora/lunr-extension'
    - '@antora/pdf-extension'

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
    kroki-plantuml-include: https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/refs/heads/main/plantuml/puml-theme-idta.puml
