site:
  title: Asset Administration Shell Documentation
  url: https://rwth-iat.github.io/aas-specs-antora
  start_page: index::index.adoc

content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: https://github.com/admin-shell-io/aas-specs
      branches:
      - IDTA-01001-3-1_working
      start-paths: documentation/IDTA-01001
    - url: https://github.com/monsieuremre/aas-specs-mock
      branches:
      - patch-1
      start-paths:
      - reliability
      - dexpi
      - mtp
      - nametemplate
      
ui:
  bundle:
    url: https://github.com/rwth-iat/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
    
runtime:
  fetch: true
  
antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/pdf-extension'

asciidoc:
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-fetch-diagram: true
