site:
  title: Asset Administration Shell Documentation
  url: https://rwth-iat.github.io/aas-specs-antora
  start_page: index::index.adoc

content:
  edit_url: '{web_url}/blob/{refname}/{path}'
  sources:
    - url: .
      branches: HEAD
      start-paths: .
    - url: https://github.com/rwth-iat/aas-specs
      branches:
      - IgGa/add_mappings
      start-paths: documentation/IDTA-01001
    - url: https://github.com/admin-shell-io/aas-specs-api
      branches:
      - IDTA-01002-3-0_antora_ref
      - IgGa/integrate_pumls
      start-paths: documentation/IDTA-01002-3
    - url: https://github.com/admin-shell-io/aas-specs-iec61360
      branches:
      - IgGa/fix_pumls
      start-paths: documentation/IDTA-01003-a
    - url: https://github.com/admin-shell-io/aas-specs-aasx
      branches:
      - IDTA-01005-3-0_antora_ref
      - IDTA-01005-3-1_working
      start-paths: documentation/IDTA-01005
    - url: https://github.com/rwth-iat/aas-specs-security
      branches:
      - documentation
      start-paths: documentation/IDTA-01004
    - url: https://github.com/admin-shell-io/submodel-templates
      branches:
      - template-documentation
      start-paths: documentation-template/*/1/0/docs
      
ui:
  bundle:
    url: https://github.com/rwth-iat/aas-specs-antora-ui/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
    
runtime:
  fetch: true
  
antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/pdf-extension'

asciidoc:
  sourcemap: true
  extensions:
    - asciidoctor-kroki
  attributes:
    xrefstyle: short
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
    kroki-plantuml-include: https://raw.githubusercontent.com/admin-shell-io/aas-specs-antora/refs/heads/main/plantuml/puml-theme-idta.puml
    kroki-plantuml-include-paths: ./IDTA-01001/modules/ROOT/partials/diagrams:./documentation/IDTA-01001/modules/ROOT/partials/diagrams:./IDTA-01001/modules/ROOT/partials/diagrams/:./documentation/IDTA-01001/modules/ROOT/partials/diagrams/
